### ISSUE TITLE
Tone Mapping not enabled/working by default

### ISSUE THREAD

**Issue by N0Klu3** [linuxserver/docker-jellyfin#103]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Playing 4k HDR media should just work and transcode.
## Current Behavior

Currently Tone Mapping is not working or enabled by default.
## Steps to Reproduce

1. Update container
2. Enable Tone Mapping in Playback
3. Play 4k HDR content
4. It fails with "This client isn't compatible with the media and the server isn't sending a compatible media format."

This can be fixed by this post: https://forums.unraid.net/topic/80744-support-linuxserverio-jellyfin/page/9
```
mkdir -p /etc/OpenCL/vendors
echo 'libnvidia-opencl.so.1' > /etc/OpenCL/vendors/nvidia.icd
```

## Environment
**OS:** unRAID
**CPU architecture:** AMD64
**How docker service was installed:**
Official unRAID Community Apps

**Comment by tobbenb** [comment]
Uhm. Running unraid on arm64? Somehow I don't think that is correct.

I know about the tonemapping support is missing. I have just forgotten to add it, as I did with the nightly branch.

**Comment by N0Klu3** [comment]
HAHA wow I could have sworn I selected AMD64 lol.
Sorry, that's my bad. Ok I remember you mentioning that it would be added, so wasnt sure. 
Last update and I just tested it today and was like why isnt my media playing anymore... had to re-do the fix above.
