### ISSUE TITLE
Intel acceleration - QSV transcode with subtitles always output green screen with subtitles stacking onto one another

### ISSUE THREAD

**Issue by seemebreakthis** [linuxserver/docker-jellyfin#106]
I have video files with embedded subtitles (i.e. a subtitle track, not a separate .srt file).  Whenever I try to play these files in jellyfin with the Intel Quick Sync option chosen, the output is a green screen with subtitles (burned into the video) that remain visible even when the next line is shown.

These videos transcode normally either with the subtitle option switched off entirely (in which case there is no subtitle), or when 'VAAPI' or 'None' is picked in 'Hardware Acceleration' instead of 'Intel Quick Sync' (in which case the performance takes a big hit). 

# Transcoding Log

This is captured from the transcode log of a sample video file (can be downloaded via links below) to show the ffmpeg command generated by jellyfin that yields erroneous output:

    /usr/lib/jellyfin-ffmpeg/ffmpeg -c:v h264_qsv -hwaccel qsv -i file:"/media/TV Shows/The Good Place/The/The.mkv" -map 0:0 -map 0:1 -codec:v:0 h264_qsv -mpegts_m2ts_mode 1 -force_key_frames "expr:gte(t,n_forced*5)" -vf "vpp_qsv=format=nv12,subtitles='/media/TV Shows/The Good Place/The/The.mkv:si=0',setpts=PTS -0/TB" -preset 7 -look_ahead 0 -b:v 5167656 -maxrate 5167656 -bufsize 10335312 -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 ac3 -ac 2 -ab 384000 -af "asetpts=PTS-0/TB" -y "/config/data/transcodes/30345a0c6c88ba9a16dac8ce4140e387.ts"

# Sample Input and Output Video Files

The sample video file with embedded subtitles track (about 180MB in size):  [Download](https://www.stringtone.com/jellyfin_transcode_bug/The.Good.Place.S04E01.720p.NF.WEBRip.x264-GalaxyTV.mkv)

The sample output file (i.e. 30345a0c6c88ba9a16dac8ce4140e387.ts) generated by jellyfin-ffmpeg (about 1.03GB in size):  [Download](https://www.stringtone.com/jellyfin_transcode_bug/30345a0c6c88ba9a16dac8ce4140e387.ts)

# Environment

**OS**: Docker host is Synology OS
**CPU architecture**: DS-220+, so Intel Celeron J4025
**How docker service was installed**:
From the official repo using the Synology docker interface, plus [this](https://github.com/linuxserver/docker-jellyfin/issues/96#issuecomment-789768141) to install intel-media-va-driver-non-free

**Comment by tobbenb** [comment]
This should be reported upstream to Jellyfin.
Also, please don't post clearly pirated stuff.
