### ISSUE TITLE
container of arm64v8 build of 10.7.6-1 is shipping 10.7.5 server and 10.7.6 webinterface

### ISSUE THREAD

**Issue by da-anda** [linuxserver/docker-jellyfin#116]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I just updated/rebuilt the container for my RPI4 (running 64bit OS) and regardless of which tag I use (arm64v8-latest, arm64v8-version-10.7.6-1) I always seem to get a likely borked container image. All logs say that it's still running Jellyfin 10.7.5, while the webinterface is listed as 10.7.6. In the admin overview, all UPNP/DLNA clients are also listed as versoin 10.7.5, which adds to my assumption that JF itself is still entirely 10.7.5 in this image. Can't tell if any other image (32, amd, ...) is also affected, but arm64v8 certainly seems to be borked. So I suspect something went wrong when the image was built? 
------------------------------

## Expected Behavior

the container image should actually contain Jellyfin 10.7.6

## Current Behavior

image seems to ship wrong version of Jellyfin

## Steps to Reproduce

create a new container using the image

## Environment
**OS:** HomeAssistant OS 64 bit
**CPU architecture:** arm64
**How docker service was installed:**

images is fetched from dockerhub directly

## Docker logs

```
```

**Comment by tobbenb** [comment]
If I remember correctly from our internal chat, 10.7.6 is the server version, but webinterface is still 10.7.5. So it's a Jellyfin issue.

**Comment by da-anda** [comment]
all logs show 10.7.5 as server version, and 10.7.6 as webinterface version. JF guys claim their image is fine and it must be a lsio issue.

**Comment by Roxedus** [comment]
At the time of our build, they had different versions in their ppa.

**Comment by da-anda** [comment]
so new builds in the pipeline, or how should we go from here?

**Comment by joshuaboniface** [comment]
> At the time of our build, they had different versions in their ppa.

How are you guys timing/triggering your builds? Our acI is sometimes slow.

**Comment by Roxedus** [comment]
We check each hour. With the latest commit we now ensure web, server and the jellyfin package itself is the same version, on our master branch.

**Comment by da-anda** [comment]
thanks, new image is working as expected now!
