### ISSUE TITLE
Transcoding fails: libmmal_core.so missing on ARM-hf image

### ISSUE THREAD

**Issue by thismachinechills** [linuxserver/docker-jellyfin#12]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

I should be able to transcode media via Jellyfin.

## Current Behavior

Transcoding media fails.

## Steps to Reproduce

1. Attempt to cast video to Chromecast
2. Cast will fail, check logs for output below

## Environment
**OS:**  Linux    
**CPU architecture:** arm32     
**How docker service was installed:**  Docker Swarm

## Docker logs
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"myfile.mp4" -sn -codec:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -vf "scale=trunc(min(max(iw\,ih*dar)\,1920)/2)*2:trunc(ow/dar/2)*2" -pix_fmt yuv420p -preset superfast -crf 28 -maxrate 10808000 -bufsize 21616000 -profile:v high -level 4.1 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -flags -global_header -vsync -1 -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 aac -strict experimental -ac 2 -ab 192000  -y "/config/transcoding-tmp/transcodes/964bde3581489e5bb81663fb40b8c524.mkv"


/usr/lib/jellyfin-ffmpeg/ffmpeg: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory
```

**Comment by thismachinechills** [comment]
As per Discord, here's the output of `docker exec -it media_jellyfin.1.vu23eg8fkphczykix8in695wk apt-get install libraspberrypi-dev`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libraspberrypi-dev
```

**Comment by j0nnymoe** [comment]
@thismachinechills do a `apt-get update` first then try again.

**Comment by thelamer** [comment]
So this is a recent dep we need to roll into the arm images , @thismachinechills care to PR it in to master ?

**Comment by thelamer** [comment]
Please pull the latest image

**Comment by thismachinechills** [comment]
Latest image works on my end. Thanks for the quick fix and for everyone's work on these Docker images.
