### ISSUE TITLE
10.7.6: DLNA Play-to broken

### ISSUE THREAD

**Issue by kls0e** [linuxserver/docker-jellyfin#120]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

DLNA Play-to should start playing a movie on a supported DLNA device.

## Current Behavior

DLNA Play-to does not have any effect with linuxserver image. Playback of DLNA content via tv browser works. (DLNA Play-to works with jellyfin/jellyfin 10.7.6 image). --net=host is enabled for discovery.

## Steps to Reproduce

1. Browse Jellyfin with IOS app
2. Select DLNA device to play-to
3. Press play on media
4. no effect

## Environment
**OS:** Raspberry Pi OS 64 bit beta 8/2020
**CPU architecture:** arm64
**How docker service was installed:** by docker pull

## Docker logs

`
[05:25:48] [INF] [78] Emby.Dlna.Main.DlnaEntryPoint: Profile: <used profile name>, Path: <...>, isEligibleForDirectPlay: True, isEligibleForDirectStream: True
`

**Comment by Roxedus** [comment]
Please fill the rest of the template

**Comment by drizuid** [comment]
requested info not provided
