### ISSUE TITLE
Preferences: Default screen for Live TV

### ISSUE THREAD

**Issue by markster101** [linuxserver/docker-jellyfin#146]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Setting default LIve TV screen to "Channels" is not working. Once set user gets redirected to "Programs"
Strange things is that if I set the default screen to "Guide" it works fine.

## Current Behavior
User should be directed to Channels screen.

## Environment
**OS: https://docs.linuxserver.io/images/docker-jellyfin image running in Docker
**CPU architecture:** x86_64

**Comment by j0nnymoe** [comment]
This should be reported to jellyfin directly. We just package their software.
