### ISSUE TITLE
Unable to change LOG file path ENV seems to be set

### ISSUE THREAD

**Issue by Devveh2000** [linuxserver/docker-jellyfin#149]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When passing -e JELLYFIN_LOG_DIR=path - this gets overwritten by the default path
Jellyfin supports --logdir as a flag which takes precident over the ENV variable being changed but this doesn't seem to be supported in the image

## Current Behavior

JELLYFIN_LOG_DIR remains as /config/log

## Steps to Reproduce

1. Run docker with -e JELLYFIN_LOG_DIR=/newpath
2. Docker logs show the path does not change
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

x86_64 - docker installed through unraid using [lscr.io/linuxserver/jellyfin](https://github.com/orgs/linuxserver/packages/container/package/jellyfin)

## Command used to create docker container (run/create/compose/screenshot)

docker run -d --name='jellyfin' --net='bridge' -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'JELLYFIN_PublishedServerUrl'='x.x.x.x' **-e 'JELLYFIN_LOG_DIR'='/mnt/user/logFiles/jellyfinLog'** -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='022' -p '8096:8096/tcp' -p '8920:8920/tcp' -p '7359:7359/udp' -p '1900:1900/udp' -v '/mnt/user/Media/TV Shows/':'/data/tvshows':'rw' -v '/mnt/user/Media/Movies/':'/data/movies':'rw' -v '/mnt/user/Media/4K Movie/':'/data/4K':'rw' -v '/mnt/user/logFiles/jellyfinLog':'/jellyfinLog':'rw' -v '/mnt/user/appdata/jellyfin':'/config':'rw' --device=/dev/dri 'lscr.io/linuxserver/jellyfin'

## Docker logs

[09:09:56] [INF] [1] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_PublishedServerUrl, x.x.x.x]", **"[JELLYFIN_LOG_DIR, /config/log]"]**
[09:09:56] [INF] [1] Main: Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg", "--webdir=/usr/share/jellyfin/web"]

**Comment by j0nnymoe** [comment]
`/mnt/user/logFiles/jellyfinLog` will mean nothing to jellyfin as it won't know that folder within the container. Also, I don't believe that variable will work with our container.
