### ISSUE TITLE
Tag Alpha/Beta Releases due to slow release cycle

### ISSUE THREAD

**Issue by zkhcohen** [linuxserver/docker-jellyfin#151]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The current release cycle of the official Jellyfin application codebase which backs this Linuxserver project is, by modern standards, unacceptably slow. Alpha and Beta builds contain many critical features which sit stagnant for months, waiting to be pushed to the mainline.

I suggest that Linuxserver begins tagging these builds when they're released, instead of only relying on a combination of nightly and mainline releases. This would allow users to revert to a version with a known set of features easily, instead of sifting through nightly builds until they find the appropriate one.

This behavior has already been implemented for the jellyfin/jellyfin container on DockerHub, in the format  `10.8.0-beta1` or `10.8.0-alpha5`.

------------------------------

## Desired Behavior

Automatically tag Docker images appropriately in conjunction with the release of Alpha/Beta builds in the source: 
https://github.com/jellyfin/jellyfin/releases

Use the format `<release_number>-<release_type><release_type_numerical_iteration>` - ex. `10.8.0-beta1` or `10.8.0-alpha5`.

## Current Behavior

Alpha/Beta builds are not tagged forcing the use of even less reliable and more unstable nightly builds.

## Alternatives Considered

- Manually searching for the nightly build corresponding with the day that the Alpha/Beta release was created.
- Building/tagging your own builds.

**Comment by aptalca** [comment]
We pull from their ubuntu package repo and it looks like they now have a `stable-pre` branch. We'll look into it.

**Comment by aptalca** [comment]
Spoke too soon (misread on mobile). That link is for the releases, not for the repo. Upstream currently only publishes `main` (stable) and `unstable` packages on their ubuntu repo: https://jellyfin.org/downloads/

The linked page in the previous post is just links to standalone packages

**Comment by riconnite** [comment]
Don't fully understand the inner workings, but that means that the stable-pre packages, like these:
https://repo.jellyfin.org/releases/server/ubuntu/versions/stable-pre/server/
Aren't able to be pulled?

**Comment by aptalca** [comment]
They're not served in an apt repo like their stable and dev releases. They are just random binaries uploaded to a website and not suitable for ci/cd ingestion. We don't do manual builds

**Comment by j0nnymoe** [comment]
If Beta/Alpha releases start getting pushed via apt, we will look at doing this.
