### ISSUE TITLE
Add NVIDIA_VISIBLE_DEVICES environment variable to dockerfiles.

### ISSUE THREAD

**Issue by ddund** [linuxserver/docker-jellyfin#152]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Following [NVIDIA Contailer Toolkit installation guide for Podman](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#podman) and using an image with the environment variable `NVIDIA_VISIBLE_DEVICES=all` allows me to use NVENC HWA in Jellyfin. I think this would be interesting for others also using an NVIDIA GPU and Podman.

------------------------------

## Desired Behavior
This would allow access NVIDIA GPUs when running with Podman.

## Current Behavior
NVIDIA GPUs are not visible inside the container

**Comment by j0nnymoe** [comment]
This isn't something we are going to add, We already state in the readme that you need to add this variable. 
Adding this with the `all` flag would cause issues for users with multi gpu systems.

**Comment by ddund** [comment]
> This isn't something we are going to add, We already state in the readme that you need to add this variable. Adding this with the `all` flag would cause issues for users with multi gpu systems.

Yeah I was a bit to fast and didn't read all of the README. You're right.
