### ISSUE TITLE
Not working on WDMyCloudEX2Ultra

### ISSUE THREAD

**Issue by Gandulf78** [linuxserver/docker-jellyfin#154]
Hi. 
I don't succeed to run properly jellyfin on my NAS (WDMyCloudEX2Ultra) with docker. 
The config volume folders are created but empty. I cannot reach the web server either. 
For information, Plew is running on the NAS. 
I run jellyfin with following command:

docker run -d  --name=jellyfin  --user 0:0  --net=host  -e TZ=Europe/Paris  -p 8096:8096  -v jellyfin-config:/config -v jellyfin-cache:/cache -v /mnt/HD/HD_a2/Public:/media  -e JELLYFIN_PublishedServerUrl=https://jellyfin.mydomain.fr  --restart always lscr.io/linuxserver/jellyfin

I try building locally or different PID/GID but it doesn't help. 

Here are the logs from docker logs jellyfin:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Jellyfin: https://opencollective.com/jellyfin

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-gid-video: executing... 
[cont-init.d] 40-gid-video: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by benwiley4000** [comment]
I'm using the same NAS. Did you figure this out?

**Comment by benwiley4000** [comment]
Not sure if this will suit your needs but my solution was to just use the Twonky Server app officially available in the apps section of the EX2Ultra. I access it with the Bubble UPnP app on Android, which among other things is able to cast a stream to Chromecast with subtitles.
