### ISSUE TITLE
cannot start without iptables

### ISSUE THREAD

**Issue by heroes1412** [linuxserver/docker-jellyfin#156]
im using ubuntu 22.04 + firewalld (not use iptables), i cannot use the image:
docker image1425e64993e1341558d4792a41fa2acf105cb4a3eb256fd51ec9f7e97fd4d64b
docker: Error response from daemon: driver failed programming external connectivity on endpoint jellyfin (b57cf6a48621f7cebc7bbf14b4138eabcefe1daadf6284             881a3c20e0724871e1):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 8096 -j DNAT --to-destination 172.17.0.3:8096 ! -i docker             0: iptables: No chain/target/match by that name.
 (exit status 1)).

**Comment by j0nnymoe** [comment]
Docker relies on iptables. This is not a container issue, it's a host issue.
