### ISSUE TITLE
[Feature Request] Add healthcheck to Dockerfiles

### ISSUE THREAD

**Issue by daynyxx** [linuxserver/docker-jellyfin#159]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Dockerfile would include a healthcheck that curl's jellyfin's built-in health check. Added to jellyfin's own image [here](https://github.com/jellyfin/jellyfin-metapackages/issues/4)
## Current Behavior

There is no healthcheck
## Alternatives Considered

I don't believe this would negatively affect anyone not wishing to use a health check, but I believe this would be a positive addition for those wishing to better automate restarting of containers that fail.

**Comment by j0nnymoe** [comment]
We've been asked this a number of times and we still have no plans at this time to add this: https://github.com/linuxserver/docker-tautulli/issues/79#issuecomment-546721863
