### ISSUE TITLE
Dolby Vision to SDR - AMD GPU OpenCL drivers

### ISSUE THREAD

**Issue by jpslv** [linuxserver/docker-jellyfin#160]
**Graphics:** AMD Ryzen 3 4300GE with Radeon Graphics

**OS:** unRAID v6.10.3

Using **Docker**

- **Docker app:** linuxserver/jellyfin
- **Jellyfin version 10.8.1**

**Problem / issue:** Playback of Dolby Vision profile 5 streams with green / purple image when **tone mapping is enabled**. I believe official jellyfin docker app has tone mapping support (only) for Intel when transcoding DoVi profile 5 to SDR. However, tone mapping for AMD needs OpenCL runtime.

**Request:** Would it be possible to add / install OpenCL runtime via the container (for example, through a mod like linuxserver/jellyfin-amd)?

**Relevant link:** https://github.com/jellyfin/jellyfin/issues/8030#issuecomment-1169759789

Thank you for your time!

**Comment by aviallon** [comment]
I support this.
Adding rocm to the container makes it work beautifully.

**Comment by aptalca** [comment]
We already have an amd gpu mod. I don't know what rocm is, but if you let us know, we can look into adding it. Or you can PR it in there: https://github.com/linuxserver/docker-mods/tree/jellyfin-amd

**Comment by aviallon** [comment]
Good idea, I think I'll do a PR.
FYI, it's a set of libraries needed to use OpenCL on recent AMD GPUs (R9 3xx and later) with the open-source AMD driver.

**Comment by jpslv** [comment]
Please do! Thank you!

**Comment by Malinskiy** [comment]
FYI https://github.com/linuxserver/docker-mods/pull/544
I'm not sure if this should be in the same mod though since rocm only works well for vega+ and other hardware from amd might [require different packages](https://wiki.archlinux.org/title/GPGPU#AMD/ATI)

**Comment by aviallon** [comment]
@jpslv 
Remind me to do it.
I can easily forget about it 😄

**Comment by drizuid** [comment]
closed by https://github.com/linuxserver/docker-mods/pull/544
