### ISSUE TITLE
Integrate CJK fonts

### ISSUE THREAD

**Issue by anuoua** [linuxserver/docker-jellyfin#161]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Normal display CJK font.

## Current Behavior

![image](https://user-images.githubusercontent.com/11324632/180014697-cc62747f-1351-497a-a01c-e90c382e1785.png)

## Alternatives Considered

I can manuly run `apt install fonts-noto-cjk-extra` to fix it.

**Comment by aptalca** [comment]
We'll investigate. In the meantime you can use this mod:
https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by anuoua** [comment]
Any update ?

**Comment by tabris233** [comment]
I also encountered this problem

**Comment by Suwmlee** [comment]
as aptalca said 

add these commands  will help

```
  -e DOCKER_MODS=linuxserver/mods:universal-package-install
  -e INSTALL_PACKAGES=fonts-noto-cjk-extra
```

**Comment by Mr-win7** [comment]
Thanks for your investigation and solution! I've solved my problem.
If it is possible, please add the dependency in the image. Thank you.

**Comment by thespad** [comment]
We won't add it to the image because it would add ~250Mb for something most people won't use. The non-Latin font packages all fairly large.
