### ISSUE TITLE
System.UnauthorizedAccessException on version 10.8.2

### ISSUE THREAD

**Issue by lbrunkho** [linuxserver/docker-jellyfin#163]
Noticed that my Jellyfin instance started throwing system IO exceptions on the latest release of this image (v10.8.2 at the time of writing). Each time I tried to play a file I will get the following errors...
`[20:28:17] [ERR] [31] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /Sessions/Playing/Progress.
System.TypeInitializationException: The type initializer for 'Nikse.SubtitleEdit.Core.Common.Configuration' threw an exception.
 ---> System.UnauthorizedAccessException: Access to the path '/run/s6/legacy-services/jellyfin/Subtitle Edit/Dictionaries' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at Nikse.SubtitleEdit.Core.Common.Configuration.GetDataDirectory()
   at Nikse.SubtitleEdit.Core.Common.Configuration..cctor()
   --- End of inner exception stack trace ---` 

I've manually rolled back to Linuxserver.io version:- 10.8.1-1-ls171 and this seems to have fixed this temporarily. I've attached the full log file for more context.
[_jellyfin_logs.txt](https://github.com/linuxserver/docker-jellyfin/files/9238853/_jellyfin_logs.txt)

Here is my docker-compose file that is used to deploy this image. Note I'm running this behind a reverse ssl proxy hence why you don't see any http ports exposed.

`version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - JELLYFIN_PublishedServerUrl=foo.bar.com
    volumes:
      - jellyfin-config:/config
      - /tank/Multimedia:/data
    networks:
            - npm
    ports:
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped

volumes:
  jellyfin-config:
networks:
  npm:
    external: true`

**Comment by DuncanBennie** [comment]
This is resolved with the latest release ([10.8.3-1-ls173](https://github.com/linuxserver/docker-jellyfin/tree/10.8.3-1-ls173)).

**Comment by lbrunkho** [comment]
Thanks! I will update and confirm shortly.

**Comment by lbrunkho** [comment]
Updated to version:- 10.8.3-1-ls173 and confirmed problem is now fixed. 

Closing issue...
