### ISSUE TITLE
Intel Celeron J4125 not using Hardware Decoding on synology

### ISSUE THREAD

**Issue by cremonies** [linuxserver/docker-jellyfin#167]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (**hevc_qsv**) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> aac (libfdk_aac))

## Current Behavior
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (**native**) -> h264 (h264_qsv))
  Stream #0:1 -> #0:1 (aac (native) -> aac (libfdk_aac))

## Steps to Reproduce

media Info
Video
Title: 1080p HEVC SDR
Codec: HEVC
Profile: Main 10
Level: 120
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 1386 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: Eng - AAC - 5.1
Language: eng
Codec: AAC
Profile: HE-AAC
Layout: 5.1
Channels: 6 ch
Bitrate: 182 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Subtitle
Title: Eng - SUBRIP
Language: eng
Codec: SUBRIP
Default: No
Forced: No
External: No

## Environment
**OS:** Synology DSM 7.0
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**
docker compose using linuxserver. 10.8.4

crw------- 1 root root        226,   0 Aug 31 19:00 card0
crw-rw-rw- 1 root videodriver 226, 128 Aug 31 19:00 renderD128

id jellyfin
uid=1034(jellyfin) gid=100(users) groups=100(users),937(videodriver)

sudo synogroup -get videodriver
Group Name: [videodriver]
Group Type: [AUTH_LOCAL]
Group ID:   [937]
Group Members:
0:[sc-ffmpeg]
1:[jellyfin]

## Command used to create docker container (run/create/compose/screenshot)
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1034
      - PGID=100
      - TZ=
    network_mode: host
    volumes:
      - /volume1/docker/jellyfin:/config
      - /volume1/data/media/tv:/data/tvshows
      - /volume1/data/media/movies:/data/movies
    restart: unless-stopped
    devices:      
      - /dev/dri:/dev/dri
    logging:
      options:
        max-file: "10"
        max-size: "200k"

## Docker logs
[Log.txt](https://github.com/linuxserver/docker-jellyfin/files/9474054/Log.txt)
[transcodeLog.txt](https://github.com/linuxserver/docker-jellyfin/files/9474055/transcodeLog.txt)

**Comment by nyanmisaka** [comment]
**native** refers to sw decoder or hw accelerator. **hevc_qsv** refers to the qsv decoder. Both cases are correct if you can see `-hwaccel * -hwaccel_output_format *` in the ffmpeg cli.

**Comment by cremonies** [comment]
Why is it not using qsv decoder?

**Comment by nyanmisaka** [comment]
Both of them are Intel hardware decoder.

**Comment by cremonies** [comment]
Ok. It was just confusing based on the bottom page of the JELLYFIN transcoding document.
https://jellyfin.org/docs/general/administration/hardware-acceleration.html
