### ISSUE TITLE
LiveTV Playback Issues on GoogleTV Only

### ISSUE THREAD

**Issue by nweishar** [linuxserver/docker-jellyfin#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm having an issue getting LiveTV to play back on my GoogleTV devices. I'm confident the streams are working fine as they play without issue on my Android App on my phone. When I try to play the same channels on GoogleTV, the streams will either not play (when transcoding is on), or will with very choppy video (with transcoding off).

Note: All tests are performed on the same LAN network. I did test LTE on the Android and it works the same as the LAN, so I don't think thats where the issue is coming from. Also should mention that this is only happening for about half of the streams. I'm still able to play a good amount of them on GoogleTV without issue, but ones like I have listed in the logs (HGTV) always fail.

### Expected Behavior

If the streams are functioning on Android, iOS, Web Browser, I would expect that they are able to function on GoogleTV the same.

### Steps To Reproduce

1. Open GoogleTV and select Jellyfin app
2. Migrate to "Guide" under LiveTV
3. Select HGTV channel and play

### Environment

```markdown
- OS:Synology DS920+ running DSM 7.1
- How docker service was installed: Using Stacks within PortainerCE to deploy the compose file.
```

### CPU architecture

x86-64

### Docker creation

```bash
jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: Jellyfin
    network_mode: host
    environment:
      - TZ=America/Toronto
      - PUID=10**
      - PGID=10**
      - UMASK=022 #optional
      - ALLOWED_NETWORKS=3.0.0.0/8,172.0.0.0/8,192.0.0.0/8
      - JELLYFIN_PublishedServerUrl=192.168.0.3 #optional
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /volume2/docker/Config/JellyFin:/config
      - /volume1/Multimedia/Audio Library/Music:/data/Music
      - /volume1/Multimedia/Audio Library/Podcasts:/data/Podcasts
      - /volume1/Multimedia/Video Library/TV Shows:/data/TV
      - /volume1/Multimedia/Video Library/Movies:/data/Movies
      - /volume1/Multimedia/Video Library/Home Movies:/data/HomeMovies
      - /volume1/Multimedia/Video Library/Documentaries:/data/Documentaries
      - /volume1/Multimedia/Video Library/YouTube:/data/YouTube
      - /volume1/Multimedia/Literature/Books:/data/Books
      - /volume2/docker/Config/Xteve:/data/Xteve #EPG Guide Repository
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    user: root
    restart: unless-stopped
    deploy:
      resources:
        limits:
          pids: -1
```

### Container logs

```bash
Playing on Android App - Working Fine - https://pastebin.com/nURr7YCc
GoogleTV Logs - Transcoding On - Will Not Start - https://pastebin.com/x8xx3YaU
GoogleTV Logs - Transcoding Off - Choppy Play - https://pastebin.com/ubue00gW
```

**Comment by nweishar** [comment]
Zero attention... It's why I ultimately had to move to Emby. A: Cause I didn't have this issue with them. And B: You actually get support with the paid supported product. My 2 cents...

**Comment by Roxedus** [comment]
This issue should probably have been closed from day one, as nothing indicates this is a container issue.
