### ISSUE TITLE
Not able to get a "config.json" file to appear.

### ISSUE THREAD

**Issue by dyl4n20** [linuxserver/docker-jellyfin#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
version: "2.15"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    network_mode: bridge
    ports:
    - 8096:8096
    volumes:
      - /home/dlone/Configs/Jellyfin/config:/config
      - /home/dlone/Configs/Jellyfin/cache:/cache
      - /media/data/:/media/data  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    network_mode: bridge
    ports:
    - 8096:8096
    volumes:
      - /home/dlone/Configs/Jellyfin/config:/config
      - /home/dlone/Configs/Jellyfin/cache:/cache
      - /media/data/:/media/data
      
      As you can see my current jellyfin docker-compose volume for the config is a directory i need to change this to a .json file but it wont let me.
      I am trying to follow the tutorial below 
https://jellyfin.org/docs/general/clients/web-config/

### Expected Behavior

i would like to replace the config directory into a j.son file but the instructions provided by jellfin don't seem to be working. 

### Steps To Reproduce

1. use my docker-compose.
2. try to get this working.

### Environment

```markdown
- OS:Windows 10 Hyper V vm on Ubuntu 22.04 with docker.
- How docker service was installed: docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
n/a
```

### Container logs

```bash
n/a
```

**Comment by j0nnymoe** [comment]
That's not our container.
