### ISSUE TITLE
[FEAT] add yt-dlp to use "Youtube Metadata Plugin for Jellyfin"

### ISSUE THREAD

**Issue by notDavid** [linuxserver/docker-jellyfin#196]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please add [yt-dlp](https://github.com/yt-dlp/yt-dlp) to make the [Youtube Metadata Plugin for Jellyfin](https://github.com/ankenyr/jellyfin-youtube-metadata-plugin) work.

Thank you!

### Reason for change

The plugin does not work currently.

**Comment by Roxedus** [comment]
This is not something we will add, however, you can add it yourself. https://docs.linuxserver.io/general/container-customization#custom-scripts
