### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by whalehub** [linuxserver/docker-jellyfin#2]
I have no idea what the Jellyfin devs were thinking when they based the official Jellyfin Docker container on the Windows version and used dotnet to run it inside of it. Your Docker image, which obviously uses Jellyfin's native Linux version, runs so much better than theirs. My users have been coming to me all day telling me how much more responsive and snappy the web UI is all of the sudden and I can confirm their experience after navigating through the admin interface for a bit.

Thank you for giving this great piece of software an equally great Docker image!

**Comment by thelamer** [comment]
thanks
