### ISSUE TITLE
[FEAT] support ffmpeg hardware decoding on WSL2

### ISSUE THREAD

**Issue by nick008a** [linuxserver/docker-jellyfin#202]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

support ffmpeg hardware decoding on WSL2

### Reason for change

https://www.phoronix.com/news/FFmpeg-VA-API-Windows

### Proposed code change

https://github.com/FFmpeg/FFmpeg/commit/a9a2ddaea8318cec43ca916b6b8350f0cf14411d

**Comment by j0nnymoe** [comment]
We use the ffmpeg provided by jellyfin directly, probably best to suggest it to them.
