### ISSUE TITLE
[BUG] JELLYFIN_ Environmental Parameters are Hardcoded 

### ISSUE THREAD

**Issue by GittyBruce** [linuxserver/docker-jellyfin#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Expect that passing
```yaml
environment:
  - JELLYFIN_DATA_DIR="/config/data_2" 
  - JELLYFIN_CONFIG_DIR="/config_2" 
  - JELLYFIN_LOG_DIR="/config/log_2" 
  - JELLYFIN_CACHE_DIR="/config/cache_2" 
  - JELLYFIN_WEB_DIR="/usr/share/jellyfin/web_2"
```
Would set those parameters inside the container. Instead, they are overwritten by root/etc/s6-overlay/s6-rc.d/svc-jellyfin/run to their defaults.

Other environmental parameters such as JELLYFIN_FFmpeg__probesize apply correctly. It's only these hardcoded ones that don't.

### Expected Behavior

Env variables are set.

### Steps To Reproduce

Run the attached docker-compose segment. Check logs for the env variables.

### CPU architecture

x86-64

### Docker creation

```bash
Jellyfin:
    image: linuxserver/jellyfin
    container_name: 'jellyfin'
    volumes:
      - $DOCKERDIR/jellyfin:/config
      - /tmp/jellyfin/cache:/cache
      - /tmp/jellyfin/transcodes:/transcodes
      - /tmp/jellyfin/log:/log
      - $DATADIR:/media
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - PUID=1000
      - PGID=1000
      - "TZ=America/Los_Angeles"
      - "JELLYFIN_LOG_DIR=/log"
      - JELLYFIN_FFmpeg__probesize=500M
      - JELLYFIN_FFmpeg__analyzeduration=250M
```

### Container logs

```bash
2023-07-09 23:58:18.165 +00:00] [INF] [6] Main: Jellyfin version: "10.8.10"
[2023-07-09 23:58:18.183 +00:00] [INF] [6] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config]", "[JELLYFIN_DATA_DIR, /config/data]", "[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_FFmpeg__probesize, 500M]", "[JELLYFIN_FFmpeg__analyzeduration, 250M]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_WEB_DIR, /usr/share/jellyfin/web]"]
```

**Comment by aptalca** [comment]
Our container was not designed to have those settings user configurable and they are not listed as valid env vars in our readme.

**Comment by GittyBruce** [comment]
Gotcha. Feel free to close then, though it is odd to override those parameters without documentation, especially since they're Jellyfin parameters and not container parameters. There are certainly several other environmental parameters Jellyfin accepts that aren't listed in the readme.
