### ISSUE TITLE
[BUG] Nightly builds seem to have stopped 19 days ago

### ISSUE THREAD

**Issue by jarylc** [linuxserver/docker-jellyfin#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
External trigger running off of nightly branch. To disable this trigger, set a Github secret named PAUSE_EXTERNAL_TRIGGER_JELLYFIN_NIGHTLY
External version: 20230720.4-unstable
Last pushed version: 20230703.12-unstable
New version 20230720.4-unstable found; but the last build was less than 6 hours ago; skipping trigger
```

### Expected Behavior

Nightly builds should continue

### Steps To Reproduce

Not applicable

### Environment

```markdown
Not applicable
```

### CPU architecture

x86-64

### Docker creation

```bash
Not applicable
```

### Container logs

```bash
Not applicable
```

**Comment by aptalca** [comment]
https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-jellyfin/activity

**Comment by thespad** [comment]
They merged a PR upstream that has completely broken their networking config and nobody seems to have noticed/cared, but it's causing our CI tests to fail.

**Comment by jarylc** [comment]
Ah, I see. I didn't check the Jenkins logs.

Seems more of an upstream issue in that case, shall I leave this issue open to track this?

**Comment by thespad** [comment]
Upstream issue https://github.com/jellyfin/jellyfin/issues/10070

**Comment by drizuid** [comment]
closing as we do not offer support for our nightly tags and this is an upstream issue but was also resolved by upstream 14 hours ago.
