### ISSUE TITLE
[FEAT] Un-hardcode the environmental parameters

### ISSUE THREAD

**Issue by fsackur** [linuxserver/docker-jellyfin#211]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Env vars are ignored, and incorrect values are shown in the logs.

e.g. in docker-compose:

```
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin/data
      - JELLYFIN_CACHE_DIR=/var/lib/jellyfin/cache
```

log shows:

```
Environment Variables: ["[JELLYFIN_CACHE_DIR, /config/cache]", "[JELLYFIN_DATA_DIR, /data]"
```

I see #204. @aptalca shut down that discussion. If I phrase this as a feature request, could that person please not hammer me?

### Reason for change

- I don't want cache or logs on `/`
  - Jellyfin rages on first run if the cache folder already exists, making it a chore to create symlinks on the host
  - ...and I run docker so I _don't_ have to live in a maze of twisty passages
- I don't want the next poor user to lose time trying to figure out this bug
- It's a sin to lose basic functionality from the official image

### Proposed code change

`root/etc/s6-overlay/s6-rc.d/svc-jellyfin/run`
```
JELLYFIN_DATA_DIR=${JELLYFIN_DATA_DIR:-/config/data} \
JELLYFIN_CONFIG_DIR=${JELLYFIN_CONFIG_DIR:-/config} \
JELLYFIN_LOG_DIR=${JELLYFIN_LOG_DIR:-/config/log} \
JELLYFIN_CACHE_DIR=${JELLYFIN_CACHE_DIR:-/config/cache}  \
JELLYFIN_WEB_DIR=${JELLYFIN_WEB_DIR:-/usr/share/jellyfin/web} 
```

**Comment by fsackur** [comment]
Please confirm a PR is acceptable with the code fix and an update to README.md. If not, then go ahead and close.

**Comment by nikp123** [comment]
Is there ANY sane reason to hard-code these. I am having trouble migrating from ``jellyfin/jellyfin`` because of this.

**Comment by aptalca** [comment]
Yes, we have reasons.

We don't officially support migrations between images of different devs. With that said, migration is fairly straightforward as long as you set up the new container with a different config folder first, so you can see the folder structure the new image expects. Then it's a matter of matching your existing data to the new format and restarting/recreating the container
