### ISSUE TITLE
[BUG] No playlists in mobile apps

### ISSUE THREAD

**Issue by meonkeys** [linuxserver/docker-jellyfin#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Mobile apps like Gelli, Finamp, and jellyfin-android are not showing playlists when server version 10.8.11 is used. Reverting server to 10.8.10 fixes the issue.

The bug is upstream: https://github.com/jellyfin/jellyfin/issues/10272

### Steps To Reproduce

Use version 10.8.11. (it really is that simple and reproducible)

### Environment

- OS: Ubuntu 22.04 LTS
- How docker service was installed: apt, if I recall correctly

### CPU architecture

x86-64

### Docker creation

Nothing special, just using `linuxserver/jellyfin:10.8.11` image repro's the bug and `linuxserver/jellyfin:10.8.10` does not.

### Container logs

n/a

**Comment by aptalca** [comment]
Upstream issue. Nothing for us to fix

**Comment by meonkeys** [comment]
> Upstream issue. Nothing for us to fix

Agreed, I just filed it here in case other folks ran into the same issue and were looking for a workaround.

I suppose you could pin your image to 10.8.10, or just make a note somewhere how 10.8.11 is broken.

**Comment by meonkeys** [comment]
Interesting timing there, CI bot! Upstream just fixed their issue. 10.8.12 is expected to resolve this.

How about if we just keep this open until we have a chance to test/qa the new release?

FYI, root case is apparently https://github.com/jellyfin/jellyfin/pull/10406

**Comment by meonkeys** [comment]
> 10.8.12 is expected to resolve this

It does.
