### ISSUE TITLE
[BUG] Docker image not updating to a hotfix automatically?

### ISSUE THREAD

**Issue by ProductiveAsparagus56** [linuxserver/docker-jellyfin#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

jellyfin/jellyfin has updated their docker image with a hotfix (10.8.13-1) which fixes audio, audio is broken in the latest linuxserver/jellyfin right now and the newest jellyfin/jellyfin image has already been out for 3 days. 

There have been no new bugs reported, this means that either everyone is on an old version (which has a security issue), or nobody cares about audio.

https://github.com/jellyfin/jellyfin/issues/10654

### Expected Behavior

linuxserver/jellyfin automatically updating, even when it's a hotfix release.

### Steps To Reproduce

-

### Environment

```markdown
-
```

### CPU architecture

x86-64

### Docker creation

```bash
-
```

### Container logs

```bash
-
```

**Comment by aptalca** [comment]
Also
https://github.com/linuxserver/docker-jellyfin/releases/tag/10.8.13-1-ls236

**Comment by aptalca** [comment]
Looks like they pushed an ffmpeg update to their repo after the hotfix version was pushed: https://github.com/linuxserver/docker-jellyfin/commit/61c33576998e577172b5f5fd3e8cda6b78d3930d
It's building here: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-jellyfin/detail/master/614/pipeline
When that finishes, you can pull that and give it a try.
