### ISSUE TITLE
PATH discrepancies between images

### ISSUE THREAD

**Issue by Artiume** [linuxserver/docker-jellyfin#22]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------
If shifting between jellyfin/jellyfin and linuxserver images, the internal paths don't match causing end users to mv host folders and readd libraries for their media.

layout
```
jellyfin/config/* -> linuxserver/
jellyfin/data     -> linuxserver/data/data
jellyfin/metadata -> linuxserver/data/metadata
jellyfin/root     -> linuxserver/data/root
```
https://github.com/jellyfin/jellyfin/issues/2560#issuecomment-597318273

## Expected Behavior

since they're different images, it's understandable that they wouldn't work together. Also, any changes made could have possible backwards compatibility issues.

**Comment by thelamer** [comment]
Would need to swap out this to config https://github.com/linuxserver/docker-jellyfin/blob/master/root/etc/services.d/jellyfin/run#L3

As you say though it would break current installs unless we put a migration snippet in place. 
Will think about it in the mean time.

**Comment by aptalca** [comment]
We could move that to the Dockerfile and let the user override it if necessary

**Comment by Artiume** [comment]
This can be fixed using command args

https://jellyfin.org/docs/general/administration/configuration.html

```
cmds: --datadir or -d, --configdir or -c, --cachedir or -C, --webdir, --logdir or -l

envs:
-e JELLYFIN_DATA_DIR 
-e JELLYFIN_CONFIG_DIR
-e JELLYFIN_CACHE_DIR
-e JELLYFIN_WEB_DIR
-e JELLYFIN_LOG_DIR

I havent tested this but it could be added to https://github.com/linuxserver/docker-jellyfin/pull/82
