### ISSUE TITLE
[BUG] Container not launching on ARM64

### ISSUE THREAD

**Issue by maximegmd** [linuxserver/docker-jellyfin#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Container fails during initialization.

### Steps To Reproduce

1. On an ARM64 machine (raspberry pi)
2. Use the provided docker-compose.yml
3. docker-compose up

### Environment

```markdown
- OS: Raspbian 64bits
- How docker service was installed: https://docs.docker.com/engine/install/debian/
Docker version 24.0.7, build afdd53b
```

### CPU architecture

arm64

### Docker creation

```bash
version: "3.4"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/pi/local-stack/jellyfin:/config
      - /export/NFS/Media/Series:/data/tvshows
      - /export/NFS/Media/Movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped
```

### Container logs

```bash
s6-rc-compile: fatal: invalid /etc/s6-overlay/s6-rc.d/init-jellyfin-config/type: must be oneshot, longrun, or bundle
```

**Comment by j0nnymoe** [comment]
Full container log please

**Comment by maximegmd** [comment]
This is the full log.

**Comment by maximegmd** [comment]
Additional information, it works on my other raspberry pi with a similar setup except it doesn't have pihole and openmediavault installed.

**Comment by j0nnymoe** [comment]
That would then prove the container works fine and the problem is something on your raspberry pi.

**Comment by maximegmd** [comment]
Now to figure out what it is so I can provide a solution for future readers, hopefully I figure it out, will post solution here if I do.
