### ISSUE TITLE
Remove 2021.12.16 version tag from registry

### ISSUE THREAD

**Issue by hadogenes** [linuxserver/docker-jellyfin#230]
### Wanted change

Could you remove _2021.12.16 _ version tag from registry?

### Reason for change

Auto updaters (such as [keel](https://github.com/keel-hq/keel)) are searching for new version and always find 2021.12.16 is the newest (ex. greater than 10.8.13)

### Proposed code change

None

**Comment by Roxedus** [comment]
We will not, and often cannot delete tags.
