### ISSUE TITLE
[FEAT] Stable Jellyfin with ffmpeg6

### ISSUE THREAD

**Issue by Cyberbeni** [linuxserver/docker-jellyfin#234]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Provide a new tracked version that combines Jellyfin 10.8 with ffmpeg6 in addition to latest and nightly.

### Reason for change

I wanted to try ffmpeg6 without completely screwing up my Jellyfin instance by upgrading to nightly. It didn't make any difference for the hardware/media that I have but others might benefit from it, since there is no ETA for Jellyfin 10.9, which will be bundled with ffmpeg6 by default.

### Proposed code change

```diff
diff --git a/Dockerfile b/Dockerfile
index 9882fe4..c4d822e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -23,7 +23,9 @@ RUN \
   apt-get update && \
   apt-get install -y --no-install-recommends \
     at \
-    jellyfin=${JELLYFIN_RELEASE} \
+    jellyfin-ffmpeg6 \
+    jellyfin-server=${JELLYFIN_RELEASE} \
+    jellyfin-web=${JELLYFIN_RELEASE} \
     mesa-va-drivers \
     xmlstarlet && \
   echo "**** cleanup ****" && \
```

**Comment by nyanmisaka** [comment]
This is actually a breaking change for NVIDIA users that ffmpeg6 requires a newer driver. So in official image we deferred to enable it to Jellyfin 10.9.

> NVENC headers are updated to meet the requirement of NVENC AV1 encoder,
the minimum required NVIDIA driver versions have been changed to 520/522 series.

https://github.com/jellyfin/jellyfin-ffmpeg/releases

10.9 release schedule: https://github.com/jellyfin/jellyfin/discussions/11051#discussioncomment-8562171
