### ISSUE TITLE
[BUG] Docker won't start anymore because of the Nvidia GPU

### ISSUE THREAD

**Issue by Crylia** [linuxserver/docker-jellyfin#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Docker worked fine with my 1660 for a while but now it suddenly won't start anymore

### Expected Behavior

Docker to function normal

### Steps To Reproduce

Install docker
Install nvidia driver
confirm both working
add --gpu-all in the docker params
see it not working anymore

### Environment

```markdown
- OS: Unraid 6.12.8
- How docker service was installed: Via unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='jellyfin'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Bocchi"
  -e HOST_CONTAINERNAME="jellyfin"
  -e 'JELLYFIN_PublishedServerUrl'='192.168.0.26'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8096]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png'
  -p '8096:8096/tcp'
  -p '8920:8920/tcp'
  -p '7359:7359/udp'
  -p '1900:1900/udp'
  -v '/mnt/user/Jellyfin/':'/data/tvshows':'rw'
  -v '/mnt/user/Jellyfin/':'/data/movies':'rw'
  -v '/mnt/user/Jellyfin/':'/media':'rw'
  -v '/mnt/user/jellyfin_data/':'/config':'rw'
  --gpus all 'lscr.io/linuxserver/jellyfin:latest'

15bb8699383217bc43a142677de7a0cabb4245a7db5bac531731083e485918ff
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: open failed: /proc/sys/kernel/overflowuid: permission denied: unknown.

The command failed.
```

### Container logs

```bash
None, won't start
```

**Comment by Roxedus** [comment]
This looks very much with a issue for the nvidia toolkit, and probably not a container issue.

**Comment by j0nnymoe** [comment]
Last I checked, ` --gpus all` isn't the way you do this. You need to set the nvidia runtime + the ENV's required.

**Comment by Crylia** [comment]
> Last I checked, ` --gpus all` isn't the way you do this. You need to set the nvidia runtime + the ENV's required.

This is how I had it originally, I removed it because it wouldn't work and since the exact same issue came up with `--gpus all` I figured it would be sufficient

**Comment by Crylia** [comment]
> This looks very much with a issue for the nvidia toolkit, and probably not a container issue.

So this mean's I'm out of luck?

**Comment by Crylia** [comment]
> Try reinstalling the plugin? Try an older driver version?

I tried another jellyfin docker (bbergle-jellyfin) and it works fine.

Maybe its an ubuntu related problem? Since the other docker is using debian

**Comment by j0nnymoe** [comment]
No issues here using jellyfin with Nvidia on unraid.

**Comment by Crylia** [comment]
Probably something todo with my specific setup then, I'd close it for now as switching the docker fixed it for me.
