### ISSUE TITLE
[FEAT] <Release new version of JF>

### ISSUE THREAD

**Issue by UltraHKR** [linuxserver/docker-jellyfin#246]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

JF 10.9.1 has a bunch of problems right now, they released a new version

https://github.com/jellyfin/jellyfin/releases/tag/v10.9.2

### Reason for change

Several bug fixes upstream

**Comment by thespad** [comment]
Our build pipeline is automated, we'll release a new version as soon as Jellyfin pushes it to their apt repo.

**Comment by UltraHKR** [comment]
That was fast... It got released as soon as you closed this...
