### ISSUE TITLE
[BUG] Subtitles not working on Firefox

### ISSUE THREAD

**Issue by z1R** [linuxserver/docker-jellyfin#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After an update to 10.9.* subtitles settings no longer work in Firefox. It works fine in other browsers. I have tried it in "troubleshoot" mode where every settings are default and addons are disabled but it's still broken.

### Steps To Reproduce

1. Use Firefox

### Environment

```markdown
- OS: Windows 11
- How docker service was installed:
The docker is on unraid.
```

### CPU architecture

x86-64

### Docker creation

```bash
It's on Unraid
```

### Container logs

```bash
https://pastebin.com/7CkWAyvB
```

**Comment by j0nnymoe** [comment]
This isn't going to be a container issue, you'd need to seek support from jellyfin themselves.

**Comment by z1R** [comment]
I just tested another docker and the problem is not there....

**Comment by j0nnymoe** [comment]
Just tested with ours and jellyfin went off, found the subtitles and displayed them in browser.

**Comment by z1R** [comment]
Ah sorry for not being more clear. The subtitles work, but changing from the default setting does not. If you try to make them smaller, different shaders or colors then it wont change.

**Comment by z1R** [comment]
Did you manage to reproduce that @j0nnymoe?
