### ISSUE TITLE
[FEAT] Please support for asian languages

### ISSUE THREAD

**Issue by LeXwDeX** [linuxserver/docker-jellyfin#250]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

For rendering covers that require support for Asian languages (e.g., Chinese, Japanese, Korean, etc.), additional font support is needed. You can use `apt install fonts-noto-cjk-extra` to add more support, which facilitates the creation of covers with non-English characters.

### Reason for change

If this font support is not available, the characters on the rendered cover will appear as blocks.

### Proposed code change

It's very simple, just add the step apt install fonts-noto-cjk-extra when building the Docker image.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by LeXwDeX** [comment]
> https://github.com/linuxserver/docker-mods/tree/universal-package-install

Hello, I know how to avoid this issue. I'm just suggesting that it could be built into the image by default, so there's no need to add extra steps.

**Comment by aptalca** [comment]
There are no `extra steps`. Just add the two env vars to your compose yaml or docker run.

We will not add that package because it would nearly double the size of the image.

**Comment by theggs** [comment]
@LeXwDeX 
Anyone who want the font being pre-installed can use my image: https://hub.docker.com/r/theggs/linuxserver-jellyfin-notofonts
It is totally based on linuxserver's image(credit to linuxserver), just pre-installed the fonts.

current version: theggs/linuxserver-jellyfin-notofonts:10.9.3

**Comment by z979054461** [comment]
> > https://github.com/linuxserver/docker-mods/tree/universal-package-install
> 
> Hello, I know how to avoid this issue. I'm just suggesting that it could be built into the image by default, so there's no need to add extra steps.

It not works for me. Please help
The install command is
```base
if [ -e /dev/dri/renderD128 ]; then                                
                                                                   
docker create -i -t --name Jellyfin \                              
        -p 28096:8096 -p 28920:8920 \                              
        -v /etc/localtime:/etc/localtime:ro \                                                  
        -v /usr/builtin/etc/certificate/:/ssl/:ro \                
        -v /share/Docker/Jellyfin/Config:/config:rw \              
        -v /share/Docker/Jellyfin/Cache:/cache:rw \                
        -v /share/Media:/media:rw \                                
        -v /share:/sharefolder:rw \                                
        --device=/dev/dri/renderD128 \                             
        --restart=unless-stopped \                                        
        -e DOCKER_MODS=linuxserver/mods:universal-package-install \        
        -e INSTALL_PACKAGES=fonts-noto-cjk-extra \                 
        jellyfin/jellyfin:latest                                   
                                                                   
else                                                               
                                                                   
docker create -i -t --name Jellyfin \                              
        -p 28096:8096 -p 28920:8920 \                              
        -v /etc/localtime:/etc/localtime:ro \                      
        -v /usr/builtin/etc/certificate/:/ssl/:ro \                
        -v /share/Docker/Jellyfin/Config:/config:rw \                         
        -v /share/Docker/Jellyfin/Cache:/cache:rw \                           
        -v /share/Media:/media:rw \                                           
        -v /share:/sharefolder:rw \                                           
        -e DOCKER_MODS=linuxserver/mods:universal-package-install \           
        -e INSTALL_PACKAGES=fonts-noto-cjk-extra \                            
        --restart=unless-stopped \                                            
        jellyfin/jellyfin:latest                                              
                                                                              
fi                                                                                                                                       
                                                                              
docker start Jellyfin 
```
