### ISSUE TITLE
[FEAT] <title>HOW can I find the activity.log instead of checking limited logs on website

### ISSUE THREAD

**Issue by simonchen1992** [linuxserver/docker-jellyfin#256]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

provide a way to check full activity logs

### Reason for change

current activity log is limited
![微信图片_20240627150816](https://github.com/linuxserver/docker-jellyfin/assets/38782131/b3ed2a0a-cf49-44bd-9c21-df54edd6b9e5)

**Comment by j0nnymoe** [comment]
All logs are stored in your `/config` mount.

**Comment by simonchen1992** [comment]
I cannot find any log regarding with activity...
![微信图片_20240627150816](https://github.com/linuxserver/docker-jellyfin/assets/38782131/154f0b9e-ff4c-4463-b61e-ccfecdd7bce1)

**Comment by simonchen1992** [comment]
> All logs are stored in your `/config` mount.

any updates?
