### ISSUE TITLE
[BUG] Server Timezone is incorrect

### ISSUE THREAD

**Issue by IBeTheBlueCat** [linuxserver/docker-jellyfin#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Jellyfin ignores envionment variable TZ and uses `TZ=Etc/UTC`

### Expected Behavior

Jellyfin uses `TZ=Europe/London` which is what it is set to

### Steps To Reproduce

1. Run linuxserver/docker-jellyfin using `TZ=Europe/London` under `environment:` in docker-compose.yml

### Environment

```markdown
- OS: Ubuntu Server 24.04
- How docker service was installed: docker compose
```

### CPU architecture

x86-64

### Docker creation

```bash
jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1007
      - PGID=1001
      - TZ=Europe/London
      - JELLYFIN_PublishedServerUrl=[redacted] #optional
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /mnt/pool/media:/media
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - swag
```

### Container logs

```bash
No mention of environment variables or timezones, and I would rather not obfuscate my entire log if not necessary (apologies)
```

**Comment by IBeTheBlueCat** [comment]
Not missing feedback, I am yet to receive any response or request for additional information

**Comment by j0nnymoe** [comment]
Where are you looking to see that Jellyfin is using that TZ rather than the one you set?

**Comment by j0nnymoe** [comment]
Unable to replicate myself:

```
root@jf:/# env | grep TZ
TZ=Europe/London
root@jf:/# 
```
That's with `  -e TZ="Europe/London"` in my docker run.

**Comment by IBeTheBlueCat** [comment]
Apologies for the delay, I would like to confirm that the issue was only apparent from viewing times within Jellyfin, they were all out by an hour as if I had set Etc/UTC. The environment variable was still set correctly, Jellyfin just seemed to be ignoring it.
The good news is that I have just checked to see if I can further investigate, and the time is now displaying correctly, I'm afraid I have no explanation for this but the issue can now be closed.
Thanks for your help

**Comment by JahFyahh** [comment]
I am experiencing this same issue. The linux machine, my tv, the docker set up are all showing the correct time. but when i open de app on my TV it shows UTC-time. I cannot play anything unless i turn off my ISP modem and use only my local network. Any ideas, help is greatly appriciated.
