### ISSUE TITLE
Cannot Enable Hardware Transcoding

### ISSUE THREAD

**Issue by misterjtc** [linuxserver/docker-jellyfin#29]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
The user can enable hardware transcoding out of the box.

## Current Behavior
When trying to initially enable hardware transcoding, the user is presented with the error:

"There was an error processing your request. Please try again later."

In checking the logs, this is apparently caused because the transcodes folder isn't created in the default location.

## Steps to Reproduce

1. Create container from default template on docker hub
2. Try the enable hardware transcoding
3. The error is presented

## Environment
**OS:**      Ubuntu 18.04 LTS
**CPU architecture:** x64      
**How docker service was installed:**
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh      

## Command used to create docker container (run/create/compose/screenshot)

docker create \
  --name=jellyfin \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Toronto \
  -e UMASK_SET=022 `#optional` \
  -p 8096:8096 \
  -p 8920:8920 `#optional` \
  -v /mnt/appdata/jellyfin:/config \
  -v /mnt:/data \
  --device /dev/dri:/dev/dri `#optional` \
  --restart unless-stopped \
  linuxserver/jellyfin

**Comment by j0nnymoe** [comment]
Try chown'ing your `/dev/dri` to the same user as the one you're using for PUID/PGID.

**Comment by Artiume** [comment]
Rpi4 doesn't have a /dev/dri device and you're missing the libraries from the host.


--device /dev/vchiq:/dev/vchiq `#optional` \ --device /dev/video10:/dev/video10 `#optional` \ --device /dev/video11:/dev/video11 `#optional` \ --device /dev/video12:/dev/video12 `#optional` \ 

-v /opt/vc/lib:/opt/vc/lib  

These are needed for Rpi4

**Comment by misterjtc** [comment]
I read the documentation on docker hub. I am not using a rpi4. I am using an hp290 with Intel Quicksync which is why I passed through /dev/dri.

I was able to solve the issue easily but checking the logs and creating the transcodes folder. However, in the spirit of ease of use and automation I thought I would report my findings here.

I will check PUID and GUID against ownership of /dev/dri and report back.

**Comment by Artiume** [comment]
Sorry, not sure why i thought you were using an rpi4.

So the transcoding directory wasn't created? That's odd. It should point to an existing dir or create it.

**Comment by j0nnymoe** [comment]
> 
> 
> I am using an hp290 with Intel Quicksync which is why I passed through /dev/dri.
> 
Oh, you need to select vaapi rather than quicksync within jellyfin.

**Comment by misterjtc** [comment]
@j0nnymoe yea that was also an issue. Maybe that was the initial issue? I don't actually know.

I just got back to testing this and here is what I did:

1. Initial I tried to enable Intel Quicksync in Jellyfin. It wouldn't let me.
2. Logs lead me to create the transcodes folder
3. Tried to play video that requires transcoding and it fails.
4. Switched from Intel Quicksync to Vaapi as suggested and transcoding appears to work.

Unfortuantely I cant say whether the transcodes folder would have been an issue had I skipped trying to enable quicksync and went to vaapi instead.

Is there a reason that I cant use Intel Quicksync when my system has Quicksync? Do either of you know if there will be a performance penalty using Vaapi vs. Quicksync?

**Comment by aptalca** [comment]
In this context, quicksync is a windows thing. On Linux only vaapi is supported with igpu.

**Comment by Artiume** [comment]
Yes and no. We need to fix our ffmpeg to properly be compiled with libmfx to use qsv on linux

https://github.com/jellyfin/jellyfin-ffmpeg/issues/16

**Comment by aptalca** [comment]
This is so confusing. Intel's ffmpeg fork [that talks about qsv](https://github.com/Intel-FFmpeg-Plugin/Intel_FFmpeg_plugins/wiki/Working-with-Open-Source-MediaSDK-and-iHD-driver-for-QSV-codecs) links to the [vaapi driver](https://github.com/intel/media-driver) when you click on the driver link

**Comment by Artiume** [comment]
So the way it works is it'll use basically the same frontend api for vaapi but instead of using libva, it'll use libmfx. I don't have hardware that supports vaapi so I only know by researching for the Jellyfin documentation

**Comment by aptalca** [comment]
Gotcha. So from our perspective, we won't have to add any additional packages, drivers or libraries as long as we're pulling in jellyfin's ffmpeg? Intel's site only references the intel va driver which we already have.

**Comment by misterjtc** [comment]
I have everything working, so thank you very much for your help.

I have a couple of quicksync boxes so if you guys are looking to do any testing, I'd be happy to help.

Let me know.

**Comment by Artiume** [comment]
If you want to see if there's anything you want to add here, that'd be great

https://jellyfin.org/docs/general/administration/hardware-acceleration.html

There's a lot of hardware available and ways to enable hwa so there's always stuff to add. Hwa with and without docker. What OS is being used and so on. I want to say Windows is a weak subject for the hwa community. Like I'm not sure how docker on windows would work out.

**Comment by TwoBall** [comment]
you can try
 chmod 666 /dev/dri/renderD128
