### ISSUE TITLE
Add support for LDAP + TLS_CACERT

### ISSUE THREAD

**Issue by sepo83** [linuxserver/docker-jellyfin#40]
I am using Jellyfin with LDAP + TLS (ldaps). My LDAP-Server is a SAMBA4 AD and uses a self-signed certificate. For enabling this in the Jellyfin Container I have to:
- edit /etc/ldap/ldap.conf --> add path to certificate 
(seems that certificate has to be downloaded to /etc/ssl/certs/)
```
#
# LDAP Defaults
#


# See ldap.conf(5) for details
# This file should be world readable but not world writable.

BASE    dc=example,dc=com
URI     ldaps://my-server.example.com

#SIZELIMIT      12
#TIMELIMIT      15
#DEREF          never

# TLS certificates (needed for GnuTLS)
TLS_CACERT      /etc/ssl/certs/ca-ldap-certificates.crt
```
- download certificate to path configured above; e.g.:
`openssl s_client -showcerts -connect my-server.example.com:636 -servername myserver </dev/null 2>/dev/null >/etc/ssl/certs/ca-ldap-certificates.crt`

However, when I recreate the container, e.g. for updates, this configuration is of course gone.

Would it be possible to modify the image in a way that this configuration is added permanently, e.g. by moving this config to /config?

I already tried to mount a volume to /etc/ldap; so at least my ldap.conf is not deleted. However, it seems that the certificate has to be installed to /etc/ssl/certs/... I am not sure if it is a good idea to add a volume mount there.

**Comment by tobbenb** [comment]
You could use our option to customize the containers detailed in the blog post https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by sepo83** [comment]
short update:
A better way is to actually install the certificate:
1. mount `/usr/local/share/ca-certificates` as volume
1. store/download the certificate to this volume
1. run `update-ca-certificates`

In order to customize the container I would have to add the volume mount and adapt the init-scripts in order to execute `update-ca-certificates` (where exactly?), right?
