### ISSUE TITLE
Jellyfin doesn't recognize that new media is imported unless Scan Library is ran manually

### ISSUE THREAD

**Issue by akhoa12** [linuxserver/docker-jellyfin#56]
Hi all, it seems Jellyfin doesn't recognize that new media is imported (real time monitoring is enabled) and only update it when library is scan manually.

## Expected Behavior
New media is picked at real-time automatically and added into library.

## Current Behavior
New media is not picked even with real-time monitoring enabled; it is only picked when Scan Library is ran manually.

## Steps to Reproduce
1. Add new media into library, with real-time monitoring enabled
2. Wait a few minutes of media to be recognised
3. New media will not be recognised until scan library task is activated

## Environment
**OS:** Linux Mint 20
**CPU architecture:** x86_64
**Docker image:** linuxserver/docker-jellyfin 10.6.1-1-ls65  

## Command used to create docker container (run/create/compose/screenshot)
docker-compose

## Docker logs
Not sure if logs are going to be useful here.

**Comment by Legogris** [comment]
This should be reported in the jellyfin project repo: github.com/jellyfin/jellyfin/
