### ISSUE TITLE
Documentation should call out DLNA and auto-discovery ports as optonal

### ISSUE THREAD

**Issue by wolflarson** [linuxserver/docker-jellyfin#59]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
We should update the documentation to tell end users about optional available ports that add functionality to the application.

## Current Behavior
Documentation does not currently tell users they can enable DLNA and service discovery per upstream documentation.

## Steps to Reproduce
https://jellyfin.org/docs/general/networking/index.html

## Environment
**OS:** NA
**CPU architecture:** NA
**How docker service was installed:**      NA

## Command used to create docker container (run/create/compose/screenshot)
NA

## Docker logs
NA

**Comment by nemchik** [comment]
Closed in https://github.com/linuxserver/docker-jellyfin/pull/61
