### ISSUE TITLE
10.6.4-1-ls85 not starts (10.6.4-1-ls84 working fine)

### ISSUE THREAD

**Issue by jellyfinuser** [linuxserver/docker-jellyfin#72]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
upgrade from 10.6.4-1-ls84 working fine to 10.6.4-1-ls85 and work fine.

## Current Behavior
Version 10.6.4-1-ls85 not start ever

## Steps to Reproduce
1. Execute a docker jellyfin container 10.6.4-1-ls85 never starts, it still ever in "services.d[done]" and web not start.

## Environment
**OS:** Linux raspberrypi 5.4.72-v7l+
**CPU architecture:**armv7
**How docker service was installed:**
OMV repo provider
## Command used to create docker container (run/create/compose/screenshot)
version: "2"
services:
  jellyfin2:
    image: linuxserver/jellyfin
    container_name: jellyfin2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 8097:8096
    restart: unless-stopped

## Docker logs
Creating jellyfin2 ... done
Attaching to jellyfin2
jellyfin2    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
jellyfin2    | [s6-init] ensuring user provided files have correct perms...exited 0.
jellyfin2    | [fix-attrs.d] applying ownership & permissions fixes...
jellyfin2    | [fix-attrs.d] done.
jellyfin2    | [cont-init.d] executing container initialization scripts...
jellyfin2    | [cont-init.d] 01-envfile: executing...
jellyfin2    | [cont-init.d] 01-envfile: exited 0.
jellyfin2    | [cont-init.d] 10-adduser: executing...
jellyfin2    |
jellyfin2    | -------------------------------------
jellyfin2    |           _         ()
jellyfin2    |          | |  ___   _    __
jellyfin2    |          | | / __| | |  /  \
jellyfin2    |          | | \__ \ | | | () |
jellyfin2    |          |_| |___/ |_|  \__/
jellyfin2    |
jellyfin2    |
jellyfin2    | Brought to you by linuxserver.io
jellyfin2    | -------------------------------------
jellyfin2    |
jellyfin2    | To support the app dev(s) visit:
jellyfin2    | Jellyfin: https://opencollective.com/jellyfin
jellyfin2    |
jellyfin2    | To support LSIO projects visit:
jellyfin2    | https://www.linuxserver.io/donate/
jellyfin2    | -------------------------------------
jellyfin2    | GID/UID
jellyfin2    | -------------------------------------
jellyfin2    |
jellyfin2    | User uid:    1000
jellyfin2    | User gid:    1000
jellyfin2    | -------------------------------------
jellyfin2    |
jellyfin2    | [cont-init.d] 10-adduser: exited 0.
jellyfin2    | [cont-init.d] 30-config: executing...
jellyfin2    | [cont-init.d] 30-config: exited 0.
jellyfin2    | [cont-init.d] 40-gid-video: executing...
jellyfin2    | [cont-init.d] 40-gid-video: exited 0.
jellyfin2    | [cont-init.d] 99-custom-scripts: executing...
jellyfin2    | [custom-init] no custom files found exiting...
jellyfin2    | [cont-init.d] 99-custom-scripts: exited 0.
jellyfin2    | [cont-init.d] done.
jellyfin2    | [services.d] starting services
jellyfin2    | [services.d] done.

**Comment by aptalca** [comment]
see #71

**Comment by richardrey** [comment]
The solution is perfect, the problem is apply solution.

the repository keys is bad, your need install signature keys and aplication manually, in my case.

for install keys your need download .deb of repository official

```
curl -O http://http.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2019.1_all.deb
```
now we will instalation of the .deb previusly download.

```
dpkg -i debian-archive-keyring_2019.1_all.deb
```

Add this repository in your list the repository.

```
echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
```

update package list.

```
apt update
```

check existence of the package.

```
apt list libseccomp2 -a
```

Install package.

```
apt install -t buster-backports libseccomp2
```

Restart the container Jellyfine.

```
docker-compose restart
```

To Enjoy

**Comment by jellyfinuser** [comment]
Sorry for the delay, It works! thanks.
