### ISSUE TITLE
Latest release doesn't work on Raspberry Pi, manually using a previous one does work

### ISSUE THREAD

**Issue by rhortal** [linuxserver/docker-jellyfin#74]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

The application starts in port 8096

## Current Behavior

Log shows no errors and progresses to 

[services.d] starting services,
[services.d] done.,

No more log messages and the application is not available no matter how long one waits for it to start.

An older image (linuxserver/jellyfin:20200722.17-unstable-ls92) works as expected.

## Steps to Reproduce

1. Use the docker-compose configuration as displayed in the instructions at the Docker Hub page in a yml file
2. docker-compose up -d jellyfin

## Environment
**OS:** Raspbian Buster / OpenMediaVault 5.5.17-3
**CPU architecture:** arm32
**How docker service was installed:** OpenMediaVault Extras to install docker and docker-compose, yml file edited by hand

## Command used to create docker container (run/create/compose/screenshot)

  jellyfin:
    image: linuxserver/jellyfin
    hostname: ${DOCKERHOSTNAME}
    ports:
    - 8096:8096
    - 8920:8920
    - 7359:7359/udp #optional
    - 1900:1900/udp #optional
    container_name: jellyfin
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/pi/docker/config/jellyfin:/config
    - /home/pi/docker/shared:/shared
    - /home/pi/docker/storage:/storage
    - /home/pi/docker/jellyfin/transcode:/transcode
    - /home/pi/docker/jellyfin/movies:/data/movies
    - /home/pi/docker/jellyfin/movies:/movies
    - /home/pi/docker/jellyfin/music:/data/music
    - /home/pi/docker/jellyfin/music:/music
    - /home/pi/docker/jellyfin/tv:/data/tvshows
    - /home/pi/docker/jellyfin/tv:/tv
    devices:
    - /dev/dri:/dev/dri #optional
    - /dev/vcsm:/dev/vcsm #optional
    - /dev/vchiq:/dev/vchiq #optional
    - /dev/video10:/dev/video10 #optional
    - /dev/video11:/dev/video11 #optional
    - /dev/video12:/dev/video12 #optional

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Jellyfin: https://opencollective.com/jellyfin

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-gid-video: executing... 
[cont-init.d] 40-gid-video: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by rhortal** [comment]
Forgot to mention it's a Raspberry Pi 4

**Comment by Roxedus** [comment]
https://docs.linuxserver.io/faq

**Comment by Saroufim** [comment]
Hello, sorry to hijack this thread. I'm running Fedora IoT on RPi3B+ and libseccomp2.5 is installed already yet I still face this error. Would you like me to open a new bug report or is this already solved somewhere else? Thanks

**Comment by Roxedus** [comment]
Open a new one
