### ISSUE TITLE
Jellyfin fails to start on Fedora IoT with Podman and libseccomp2.5

### ISSUE THREAD

**Issue by Saroufim** [linuxserver/docker-jellyfin#76]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Jellyfin should start normally since libseccomp 2.5 is installed. 

## Current Behavior
Jellyfin doesn't start after the install script ends. It shows the date as 1970. 

## Steps to Reproduce
1. Install Fedora IoT
2. Install Jellyfin with Podman
3. Wait for Install Script to end
4. Navigate to the web ui and notice that jellyfin doesn't start

## Environment
**OS:** Fedora IoT 
**CPU architecture:** arm32
**How docker service was installed:**
Podman was installed already on the base image and Jellyfin was pulled from Docker Hub.

## Command used to create docker container (run/create/compose/screenshot)
`podman run -d --security-opt label=disable --name=jellyfin -e PUID=1000 -e PGID=1000 -e TZ=Asia/Beirut -e UMASK_SET=022 -p 8096:8096 /home/user/.jellyfin:/config -v /home/user/media:/data/ --device /dev/vchiq:/dev/vchiq  --restart unless-stopped ghcr.io/linuxserver/jellyfin`

## Docker logs
```
  GNU nano 5.3                                                                                                  /var/home/pi/jelly.log                                                                                                             
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Jellyfin: https://opencollective.com/jellyfin

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-gid-video: executing...
[cont-init.d] 40-gid-video: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by Roxedus** [comment]
Libseccomp 2.5.1 or 2.5? 2.5 arrived before 2.4.4 which fixes it for Debian

**Comment by Saroufim** [comment]
`libseccomp-2.5.0-3.fc33.armv7hl`

I will wait for the 2.5.1 update and I will report back.

**Comment by Saroufim** [comment]
The lib hasn't been updated yet so I cannot say if it provides the fix or not.

**Comment by Saroufim** [comment]
An update was pushed that fixed it.
