### ISSUE TITLE
Official Container Image Naming (RC)

### ISSUE THREAD

**Issue by vegedb** [linuxserver/docker-jellyfin#79]
[RC1](https://reddit.com/r/jellyfin/comments/k72umj/jellyfin_1070_release_candidate_1/)

Here is the quote,

> The second is for Docker users: the RC is at a new tag, stable-rc, with this particular version being 10.7.0-rc1. This ensures that users on the latest tag aren't in for a sudden surprise upgrade. Like the Debuntu users, you must manually enable this tag to help test, then switch again to the latest tag for the final release.

![image](https://user-images.githubusercontent.com/72070424/101272735-feef9380-37c9-11eb-8eb4-24e43731b894.png)

![image](https://user-images.githubusercontent.com/72070424/101272717-bdf77f00-37c9-11eb-8f97-d059aa4a1d3c.png)

Hope you change to their naming convention, I'm totally confused as to which is which in your [dockerhub](https://hub.docker.com/r/linuxserver/jellyfin/tags)

**Comment by aptalca** [comment]
There is nothing confusing about it. Our `latest` is built from their stable repo and our `nightly` is built from their unstable repo. They are both listed in our readme.

The docker hub images are all tagged with the upstream version numbers as they appear in their repos.

Their release candidates are not in any of their repos therefore we won't be building them.

**Comment by vegedb** [comment]
@aptalca 
I see that's a shame.
I have an issue changing to the official container (RC). It simply doesn't read my previous library (config,cache) made using linuxserver. I only changed the image to **jellyfin/jellyfin** from linuxserver/jellyfin.

How do you convert linuxserver to the official container?

**Comment by aptalca** [comment]
Switching between our and others' images is not something we support. You should probably set up a fresh instance of the other container, compare their persistent folder structure to ours and make any necessary changes. But that's about the extent of the support we can provide.

**Comment by vegedb** [comment]
As far as I can see there's no issue on the volumes as they are the exact same. I can **docker exec bash** and see the folders/contents are there. I'm stuck.

**Comment by Extarys** [comment]
I'm also trying to migrate right now.
Current issue from what I understand is I mounted the config directory for the linuxserver image like so:
`- /storage/containers/jellyfin/config:/config`

```
/storage/containers/jellyfin/config$ ls -la
total 68
drwxr-xr-x 8 ubuntu ubuntu 4096 Dec  3 11:31 .
drwxr-xr-x 4 ubuntu ubuntu 4096 Jul  7 13:13 ..
drwxr-xr-x 2 ubuntu ubuntu 4096 Dec  4 20:04 ScheduledTasks
-rw-r--r-- 1 ubuntu ubuntu  251 Nov 30 11:12 branding.xml
drwxr-xr-x 8 ubuntu ubuntu 4096 Dec  4 20:49 cache
drwxr-xr-x 7 ubuntu ubuntu 4096 Aug  6 19:29 data
drwxr-xr-x 4 ubuntu ubuntu 4096 Jul  7 13:14 dlna
-rw-r--r-- 1 ubuntu ubuntu 1132 Dec  5 19:08 encoding.xml
drwxr-xr-x 2 ubuntu ubuntu 4096 Dec  6 00:00 log
-rw-r--r-- 1 ubuntu ubuntu 1362 Jul  7 13:14 logging.default.json
-rw-r--r-- 1 ubuntu ubuntu  243 Nov 19 11:42 metadata.xml
-rw-r--r-- 1 ubuntu ubuntu 1333 Aug  2 13:42 migrations.xml
-rw-r--r-- 1 ubuntu ubuntu  236 Aug  6 21:11 playback_reporting.xml
-rw-r--r-- 1 ubuntu ubuntu 6768 Dec  3 10:56 system.xml
drwxr-xr-x 7 ubuntu ubuntu 4096 Jul 16 15:00 users
-rw-r--r-- 1 ubuntu ubuntu  445 Dec  3 17:54 xbmcmetadata.xml
```

But it appears the folder structure is different for the jellyfin image:
```
/storage/containers/jellyfin-broken/config$ ls -la
total 92
drwxr-xr-x 12 ubuntu ubuntu  4096 Dec  6 13:15 .
drwxr-xr-x  4 root   root    4096 Jul  7 13:13 ..
drwxr-xr-x  2 ubuntu ubuntu  4096 Dec  4 20:04 ScheduledTasks
-rw-r--r--  1 ubuntu ubuntu   251 Nov 30 11:12 branding.xml
drwxr-xr-x  8 ubuntu ubuntu  4096 Dec  4 20:49 cache
drwxr-xr-x  3 root   root    4096 Dec  6 13:15 config
drwxr-xr-x  9 ubuntu ubuntu  4096 Dec  6 13:15 data
drwxr-xr-x  4 ubuntu ubuntu  4096 Jul  7 13:14 dlna
-rw-r--r--  1 ubuntu ubuntu  1132 Dec  5 19:08 encoding.xml
drwxr-xr-x  2 ubuntu ubuntu 12288 Dec  6 13:19 log
-rw-r--r--  1 ubuntu ubuntu  1362 Jul  7 13:14 logging.default.json
drwxr-xr-x  2 root   root    4096 Dec  6 13:14 metadata
-rw-r--r--  1 ubuntu ubuntu   243 Nov 19 11:42 metadata.xml
-rw-r--r--  1 ubuntu ubuntu  1333 Aug  2 13:42 migrations.xml
-rw-r--r--  1 ubuntu ubuntu   236 Aug  6 21:11 playback_reporting.xml
drwxr-xr-x  3 root   root    4096 Dec  6 13:15 plugins
drwxr-xr-x  3 root   root    4096 Dec  6 13:15 root
-rw-r--r--  1 ubuntu ubuntu  6768 Dec  3 10:56 system.xml
drwxr-xr-x  7 ubuntu ubuntu  4096 Jul 16 15:00 users
-rw-r--r--  1 ubuntu ubuntu   445 Dec  3 17:54 xbmcmetadata.xml
```
Notice the `config` folder in there.
```
/storage/containers/jellyfin-broken/config/config$ ls
dlna  encoding.xml  logging.default.json  migrations.xml  network.xml  system.xml
```
This is not a clean install it was an attempt at migrating. Some files are moved in their own config folder.

**Comment by Extarys** [comment]
To migrate, assuming you have a volume mounted like so:
```
/storage/jellyfin/config:/config
/storage/jellyfin/cache:/cache
```


**Stop the container**
I should have also maybe disabled the plugins as they caused some errors at startup but, well.

Create a backup: 
- Delete everything in the ./transcode folder.
`tar -cv -I 'xz -8 -T0' -f /storage/containers/jellyfin-old.tar.xz /storage/jellyfin`

Go to `/storage/jellyfin/config` All commands must be typed from there.
```
mkdir config
mv encoding.xml logging.default.json metadata.xml migrations.xml system.xml branding.xml dlna ./config


mv ./data/metadata ./metadata
mv ./data/root ./root
mv ./data/transcodes ./transcodes
mv ./data/plugins ./plugins
mv ./data/data ./data2
rmdir ./data
mv ./data2 ./data

mv ./ScheduledTasks ./data/ScheduledTasks
mv ./cache ../

# NOT SURE

mv xbmcmetadata.xml playback_reporting.xml ./config
```

Change `image:linuxserver/jellyfin:latest` to `image:jellyfin/jellyfin:stable-rc`
Start the container.

Worked for me, all users are there and my progress too. I didn't test plugins yet but it should work also.

If you messed up, or I messed up - remove jellyfin folder and extract your backup:
```
rm -rf ./jellyfin
tar -xf jellyfin-old.tar.xz ./jellyfin
```
@vegedb

**Comment by Extarys** [comment]
@aptalca The RC release is in the jellyfin repo: https://github.com/jellyfin/jellyfin/releases/tag/v10.7.0-rc1

Or did you mean something else?

**Comment by aptalca** [comment]
@Extarys 
I'm referring the to debian/ubuntu package repos

**Comment by faizpuru** [comment]
To migrate, I just had to define these variables in my docker compose :
```
- JELLYFIN_DATA_DIR=/config/data
- JELLYFIN_CONFIG_DIR=/config
- JELLYFIN_LOG_DIR=/config/log
- JELLYFIN_CACHE_DIR=/config/cache
```

**Comment by Extarys** [comment]
@faizpuru Yeah I had to restore my backup and do the same.
Some paths are hardcoded into the database for each file in a BLOB column, which make it very difficult to change.
