### ISSUE TITLE
How to get the latest version 10.7.0-rc1

### ISSUE THREAD

**Issue by kopax** [linuxserver/docker-jellyfin#80]
## Expected Behavior

I would like to access the latest version of jellyfin

## Current Behavior

The latest version is the latest stable one

## Description

According to https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/56#issuecomment-743343541

I am using the Linux server version of jellyfin: https://hub.docker.com/r/linuxserver/jellyfin
While the official version is: https://hub.docker.com/r/jellyfin/jellyfin/tags?page=1&ordering=last_updated

Jellyfin 10.7 is currently in RC1, and available in the official container image jellyfin/jellyfin:10.7.0-rc1

I did not pay attention because I tough the linuxserver image was a better quality with a better concept, how can we get the latest version of jellyfin using your image?

**Comment by Roxedus** [comment]
We don't offer their RC's, as mentioned here https://github.com/linuxserver/docker-jellyfin/issues/79#issuecomment-739460609

**Comment by kopax** [comment]
Ok, ill wait until it gets tagged without it. Do you often perform new versions release ? You look to have a bunch of images to maintain

**Comment by Roxedus** [comment]
Our army of bots check every hour https://github.com/linuxserver/docker-jellyfin/blob/master/.github/workflows/external_trigger_scheduler.yml#L5

**Comment by aptalca** [comment]
Since we maintain hundreds of images, we stay away from manual updates. Jellyfin decided to make RC installs a manual affair, therefore we won't be pushing it (until it hits one of the apt package repos)

**Comment by kopax** [comment]
Thanks a lot, awesome work by the way
