### ISSUE TITLE
Webserver wont boot

### ISSUE THREAD

**Issue by kostak79** [linuxserver/docker-jellyfin#83]
Since the last Updates the Webserver of Jellyfin dont start any more.
The Last functional Version was the jellyfin:10.6.4-1-ls82. Any Version after this wont work.
i use an RBP4 with OMV 5.x

Regards ans thx

**Comment by Roxedus** [comment]
Same answer as you got on your plex issue, also, please, please use the issue template.

**Comment by kostak79** [comment]
Problem solved with changing the Tag to bionic. Thx.

**Comment by kostak79** [comment]
> Same answer as you got on your plex issue, also, please, please use the issue template.

Next time for sure. Sorry for that.
