### ISSUE TITLE
[Feature / Update] Jellyfin now supports VAAPI for Raspberry Pi

### ISSUE THREAD

**Issue by blmhemu** [linuxserver/docker-jellyfin#84]
The guide shows that RPI currently supports v4l2 and OpenMAX. But the newer jellyfin release seems to support VA-API.
It requires the user to be added in "render" group.
Please have a look at 
https://jellyfin.org/docs/general/administration/hardware-acceleration.html
and 
https://www.reddit.com/r/jellyfin/comments/jhwt49/vaapi_hardware_transcoding_working_on_the/
Looks like HEVC decoding is also supported !

**Comment by aptalca** [comment]
Can you try mapping `/dev/dri` and see if it works? The device ownership logic is already there

**Comment by blmhemu** [comment]
I tried to list all groups (cat /etc/group) and was not able to see any group named "render".
And yes i tried mapping the /dev/dri folder and tried to play 4k hevc file. But it did not even open !

**Comment by aptalca** [comment]
Don't worry about the groups, the container handles that automatically.

Do this for me on the host:
`ls -al /dev/dri`

**Comment by blmhemu** [comment]
Question : Are the VA API driver / libraries installed by default ?
Will post the answers soon (My rpi takes a long time to boot)

**Comment by blmhemu** [comment]
Here are the details: 
![image](https://user-images.githubusercontent.com/19410501/102717388-06558780-4308-11eb-97df-0679bb2dda74.png)

**Comment by aptalca** [comment]
Yup, the container should handle the permissions properly.

The links you posted are very thin on the technical details. They just say it works on ubuntu server but not desktop (no clue why that would be the case), and no mention of any drivers.

**Comment by blmhemu** [comment]
Yeah the details are thin. But I am assuming for the moment that `dtoverlay=vc4-kms-v3d-pi4` is where it gets the drivers.

**Comment by nyanmisaka** [comment]
https://github.com/jellyfin/jellyfin-docs/pull/484

There is no VAAPI support on Raspberry Pi. VAAPI is only possible on Intel, AMD and Nvidia.
The video core on Broadcom chips can be accessed via OpenMax and V4L2 until now.

Pi developers are trying unify decoder and encoder pipeline by using DRM PRIME.
For more details see https://github.com/jc-kynesim/rpi-ffmpeg/tree/dev/4.3.1/drm_prime_1
