### ISSUE TITLE
Notification settings being ignored

### ISSUE THREAD

**Issue by nbo21** [linuxserver/docker-jellyfin#9]
Changing notification settings doesn't seem to work. I have tried to disable the new content notifications, but they still show up. 

The official docker container doesn't have this problem. I am running the latest version of the docker image.

**Comment by thelamer** [comment]
We do not do anything different than the official image here the settings are specifically stored in `/config/notifications.xml`. 

Are you referring to the browser notifications that you set when you first go to the web interface in your browser? If so that is a client side setting and has nothing to do with the web application.

**Comment by nbo21** [comment]
I'm talking about the notifications setting on the server side, not the browser notifications setting:

![jellyfin1](https://user-images.githubusercontent.com/14217052/63650282-7534c780-c738-11e9-9450-031c07df2087.png)
![jellyfin2](https://user-images.githubusercontent.com/14217052/63650283-7534c780-c738-11e9-9c57-58b237cd6bae.png)

I have installed the Gotify plugin for testing and those notifications work correctly. The disabled new content notification doesn't get sent from Gotify but still shows up in the browser.
Additionally, I enabled the audio playback started setting and only Gotify sent a notification.

So it seems that only the browser notifications are not working correctly. The default settings seem to persist somehow. I tested it with Firefox and Opera but both show the same problem.

**Comment by thelamer** [comment]
Just to make 100% sure you are not blocking notifications browser side for your official Jellyfin container? 
When you get your first notification your browser asks you to allow or deny them. 

Sorry I cannot see how this could be happening we run their debs: 
https://github.com/jellyfin/jellyfin/releases/tag/v10.3.7

And this is 100% software it has nothing to do with an application being wrapped in a Docker container. Your browser using javascript talks to the web app using a websocket connection, Docker has nothing to do with these interactions.

**Comment by nbo21** [comment]
Looks like I made a mistake. I'm getting the same issue with the official container now. So it's either something on my end or a general Jellyfin issue.
