### ISSUE TITLE
Jellyfin fails to start on Portainer

### ISSUE THREAD

**Issue by NicHahn** [linuxserver/docker-jellyfin#90]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Start Jellyfin with the web UI (<ip-address>:8096)

## Current Behavior
Jellyfin doesn't start

## Steps to Reproduce

1.My stack from portainer:
---
version: "2.1"
services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Berlin
      - UMASK_SET=<022> #optional
    volumes:
      - /srv/dev-disk-by-uuid-f86e6539-21f2-4566-87ae-907f1a6e5eb9/Test/Config:/config
      - /srv/dev-disk-by-uuid-f86e6539-21f2-4566-87ae-907f1a6e5eb9/Test/Movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

## Environment
**OS: Rasperian Light OS
**How docker service was installed:**
Installed on Open Media Vault

## Docker logs
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,
./run: line 10: umask: `<': invalid symbolic mode operator,

**Comment by tobbenb** [comment]
Join our discord server or discourse forum for help. Your issue is not a bug, but a configuration problem. Your unmask is set wrong. Further help should be in the above mentioned places.
