### ISSUE TITLE
Jellyfin on open media vault via docker error

### ISSUE THREAD

**Issue by tonyelpriulas** [linuxserver/docker-jellyfin#94]
I'm trying to enable video acceleration but i'm getting this error: Error response from daemon: error gathering device information while adding custom device "/dev/vcsm": no such file or directory. I´m running a Rpi 4 with raspberry os 64 bits and omv install on it

**Comment by merc4derp** [comment]
Same here. Been this way for a couple weeks. /dev/vcsm just isn't there anymore and not getting any help from the omv guys.

**Comment by Uatschitchun** [comment]
I'd have the same question. My rpi only provides /dev/vcsm-cma, so no /dev/vcsm anymore!?
I can't find much info on this, so my question is, will it suffice to create a symlink or add the vcsm-cma to the docker?
As far as I've read, those both devices aren't ABI compatible!?

**Comment by aptalca** [comment]
I noticed that some of those devices differ from distro to distro. Libreelec also had a slightly different structure but the recommendation we list in the readme seemed to work for it.

The only way to find out is to map those devices one by one (make sure the permissions are correct) and see if they make hw transcode work and determine the lowest common denominator.

I can't test it on other distros, but if you guys do and let me know, I'd be happy to update the readme and the init script to fix the permissions.

**Comment by Uatschitchun** [comment]
It's an update within the rpi kernel that replaces vcsm with vcsm-cma. I guess that's not dependent on what distribution one is using. If I get it correct, /dev/vcsm will get completely replaced with /dev/vcsm-cma.
See:
https://github.com/raspberrypi/linux/issues/4112#issuecomment-792741563

**Comment by j0nnymoe** [comment]
This was an issue with the users host setup and not a container issue.
